/**
 * AssignedCampaigns — SDR's campaign assignment queue.
 *
 * IMPLEMENTATION INSTRUCTIONS:
 *
 * Exports: AssignedCampaigns (class)
 *
 * Constructor(container: HTMLElement):
 *   Renders the assignment list. Fetches initial data.
 *
 * Item display fields:
 *   - Campaign name
 *   - VP who created it
 *   - 2–3 sentence rationale (auto-generated by Hub from VP's original command)
 *   - Count of assigned accounts for this SDR
 *
 * Three-state item lifecycle per assignment:
 *   1. 'pending'   → show "Review" button (blue)
 *   2. 'in-review' → expanded state with pre-drafted email + Edit/Send buttons
 *   3. 'sent'      → grayed out with checkmark, "Sent {date}" label
 *
 * On item click (pending → in-review):
 *   - Expand to show pre-drafted emails for each account in the assignment.
 *   - Display the email for the first account, with navigation to next/prev accounts.
 *   - Load the email into an EmailEditor instance.
 *   - SDR can edit and send.
 *
 * On "Send" click:
 *   - Call hubClient.captureEdit(originalDraft, finalEdit) (edit capture).
 *   - POST to HUB_URL/webhooks/send with send details.
 *   - Update item state to 'sent'.
 *   - Every send captured = critical signal for feedback flywheel.
 *
 * Empty state:
 *   "No assignments yet. Assignments will appear here when a VP creates a campaign."
 *
 * Refresh:
 *   Called by QuickGenerate's polling interval (every 30 seconds).
 *   Method: refresh(assignments: AssignmentSummary[])
 */

export class AssignedCampaigns {
  constructor(container) {
    this.container = container;
    this.assignments = [];
    // TODO: implement per instructions above
    this.render();
  }

  render() {
    // TODO: implement DOM construction per instructions above
    this.container.innerHTML = `
      <div class="assigned-campaigns">
        <h3>Assigned Campaigns</h3>
        <div id="assignmentList" class="assignment-list">
          <p class="empty-state">No assignments yet.</p>
        </div>
      </div>
    `;
  }

  refresh(assignments) {
    // TODO: update the assignment list DOM with new data
    this.assignments = assignments || [];
    const listEl = this.container.querySelector('#assignmentList');
    if (!listEl) return;

    if (this.assignments.length === 0) {
      listEl.innerHTML = '<p class="empty-state">No assignments yet. Assignments will appear here when a VP creates a campaign.</p>';
      return;
    }

    // TODO: render each assignment item with 3-state lifecycle
    listEl.innerHTML = this.assignments.map(a => `
      <div class="assignment-item" data-id="${a.id}" data-status="${a.status}">
        <div class="assignment-header">
          <span class="campaign-name">${a.campaign_name}</span>
          <span class="vp-name">from ${a.vp_name}</span>
        </div>
        <p class="rationale">${a.rationale_snippet}</p>
        <div class="assignment-meta">${a.account_count} accounts</div>
        <button class="review-btn" data-id="${a.id}">Review</button>
      </div>
    `).join('');
  }
}
